// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports, module) {
    var GameObject;
    GameObject = (function() {
      function GameObject(name, speed) {
        this.name = name;
        this.speed = speed;
        console.log('aaa');
      }

      return GameObject;

    })();
    return GameObject;
  });

}).call(this);
