// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports, module) {
    var Mapa;
    Mapa = (function() {
      Mapa.prototype.size = 20;

      function Mapa() {
        this.map = [[1, 1, 0, 1, 1, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 1], [1, 1, 0, 1, 1, 0]];
      }

      Mapa.prototype.render = function(startX, startY, c) {
        var x, y, _i, _j, _ref, _ref1;
        c.save();
        for (y = _i = 0, _ref = this.map.length; 0 <= _ref ? _i < _ref : _i > _ref; y = 0 <= _ref ? ++_i : --_i) {
          for (x = _j = 0, _ref1 = this.map[y].length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
            if (this.map[x][y] === 1) {
              c.fillStyle = "yellow";
            } else {
              c.fillStyle = "black";
            }
            c.fillRect(startX + this.size * x, startY + this.size * y, this.size, this.size);
          }
        }
        return c.restore();
      };

      return Mapa;

    })();
    return Mapa;
  });

}).call(this);
